#!/bin/bash -exu

ROOT="${PWD}"
VERSION=$(cat "${ROOT}/az-automation-version/number")
LINUX_BUILD_PATH="${ROOT}/builds/bin/az-automation-v${VERSION}_linux_x86-64"
OSX_BUILD_PATH="${ROOT}/builds/bin/az-automation-v${VERSION}_osx"

function main() {
  local commit_sha

  mkdir -p "${GOPATH}/src/github.com/genevievelesperance/"

  ln -s "${ROOT}/az-automation" "${GOPATH}/src/github.com/genevievelesperance/"

  commit_sha=$(git -C "${ROOT}/az-automation" rev-parse HEAD)

  pushd "${GOPATH}/src/github.com/genevievelesperance/az-automation" > /dev/null

    echo "Building 64-bit Linux"

    CGO_ENABLED=0 GOARCH=amd64 GOOS=linux \
      go build -a -tags netgo -installsuffix netgo \
      -o "${LINUX_BUILD_PATH}" .

    echo "Building 64-bit Darwin"

    GOARCH=amd64 GOOS=darwin \
      go build -o "${OSX_BUILD_PATH}" .

  popd > /dev/null

  pushd "${ROOT}/builds" > /dev/null

    echo -n "v${VERSION}" > name
    echo -n "${commit_sha}" > commitish

  popd > /dev/null
}

main
