#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/genevieve"

pushd "${GOPATH}/src/github.com/genevieve" > /dev/null
  ln -s "${ROOT}/az-automation"
  ./az-automation/scripts/test
popd > /dev/null
