#!/bin/bash -exu

export ROOT="${PWD}"

function main() {
  setup_bosh_env_vars

  for i in $(bosh deployments | grep "${DEPLOYMENTS_WITH_WORD}" | awk '{ print $1 }' | uniq); do
    bosh -d $i -n delete-deployment
  done

  echo "cleaning up orphaned disks and releases"
  bosh -n clean-up --all
}

function setup_bosh_env_vars() {
  if [ -r "${ROOT}/bbl-state/${BBL_STATE_DIR}/bbl-state.json" ]; then
    set +x
    pushd "${ROOT}/bbl-state/${BBL_STATE_DIR}" > /dev/null
      eval "$(bbl print-env)"
    popd > /dev/null
    set -x
  fi
}

main
