#!/bin/bash -eu

function main() {
  local pipeline_name
  local pipeline_file
  local var_file
  local shared_env
  local vars

  pipeline_name="${1}"
  pipeline_file="${HOME}/go/src/github.com/cloudfoundry/infrastructure-ci/pipelines/${pipeline_name}.yml"
  var_file="${HOME}/go/src/github.com/cloudfoundry/infrastructure-ci-env/pipeline-vars/${pipeline_name}.yml"
  shared_env="${HOME}/go/src/github.com/cloudfoundry/infrastructure-ci-env/pipeline-vars/shared-env.yml"

  if [ -f ${var_file} ]; then
    vars="-l ${var_file}"
  fi

  fly -t wings set-pipeline -p ${1} -c ${pipeline_file} -l ${shared_env} ${vars}
}

main ${1}
