#!/bin/bash -exu

main() {
  local opsman_image=$(bosh int ${PWD}/opsman-image/*${IAAS}.yml --path "/${KEY}")
  local output_key

  local iaas_lowercase=$(echo "${IAAS}" | awk '{print tolower($0)}')
  case "$iaas_lowercase"
  aws)
    output_key=ops_manager_ami
    ;;
  gcp)
    output_key=opsman_image_url
    ;;
  azure)
    output_key=ops_manager_image_uri
    ;;
  esac

  echo "${output_key}: ${PREFIX}${opsman_image}" > "${PWD}/tfvars/terraform.yml"
}

main "$@"
