#!/bin/bash -exu

function main() {
  pushd release-repo > /dev/null
    git config user.name "CF INFRASTRUCTURE BOT"
    git config user.email "cf-infrastructure@pivotal.io"

    git remote add -f master-repo ../release-repo-master
    git merge --no-edit "master-repo/master"

    git status
    git show --color | cat
  popd > /dev/null

  shopt -s dotglob
  cp -R release-repo/* final-release-repo
}

main
