#!/bin/bash -exu

pushd terraforming-vsphere > /dev/null

  terraform init

  trap 'terraform destroy -force; exit' EXIT

  set +x
    cat > terraform.tfvars <<-EOF
		env_name = "terraforming-vsphere-env"
		om_ipv4_address = "${VSPHERE_OM_IP}"
		subnet_cidr = "${VSPHERE_SUBNET_CIDR}"
		om_gateway = "${VSPHERE_GW_IP}"
		om_dns = "${VSPHERE_OM_DNS}"
		om_ntp_servers = "${VSPHERE_OM_NTP}"
		om_template = "${VSPHERE_VCENTER_TEMPLATES}/${VSPHERE_OM_TEMPLATE}"
		om_admin_password = "${VSPHERE_OM_ADMIN_PASSWORD}"

		vcenter_user = "${VSPHERE_VCENTER_USER}"
		vcenter_password = "${VSPHERE_VCENTER_PASSWORD}"
		vcenter_server = "${VSPHERE_VCENTER_IP}"
		vcenter_dc = "${VSPHERE_VCENTER_DC}"
		vcenter_cluster = "${VSPHERE_VCENTER_CLUSTER}"
		vcenter_rp = "${VSPHERE_VCENTER_RP}"
		vcenter_ds = "${VSPHERE_VCENTER_DS}"
		vcenter_network = "${VSPHERE_NETWORK}"
		vcenter_vms = "${VSPHERE_VCENTER_VMS}"

		allow_unverified_ssl = true
EOF
  set -x

  terraform validate

  terraform plan -out=plan

  TF_LOG=TRACE TF_LOG_PATH=tf-logs.txt terraform apply plan

  terraform destroy -force

popd > /dev/null
