#!/bin/bash -exu

pushd terraforming-aws > /dev/null

  terraform init

  set +x
    echo 'env_name="terraforming-aws-env"' > terraform.tfvars
    echo "access_key = \"${AWS_ACCESS_KEY_ID}\"" >> terraform.tfvars
    echo "secret_key = \"${AWS_SECRET_ACCESS_KEY}\"" >> terraform.tfvars
    echo -e "ssl_cert = <<EOF\n${AWS_SSL_CERT}\nEOF" >> terraform.tfvars
    echo -e "ssl_private_key = <<EOF\n${AWS_SSL_PRIVATE_KEY}\nEOF" >> terraform.tfvars
    echo 'region = "us-west-1"' >> terraform.tfvars
    echo 'availability_zones = ["us-west-1a", "us-west-1c"]' >> terraform.tfvars
    echo 'ops_manager_ami = "ami-4f291f2f"' >> terraform.tfvars
    echo 'rds_instance_count = 1' >> terraform.tfvars
    echo 'dns_suffix = "terraforming-aws-env.example.com"'  >> terraform.tfvars
  set -x

  terraform plan -out=plan

  terraform apply plan

  terraform destroy -force

popd > /dev/null
