#!/bin/bash -exu

ROOT="${PWD}"

function main() {
  pushd "${ROOT}/bosh-bootloader-bumped" > /dev/null
    git config user.email "cf-infrastructure@pivotal.io"
    git config user.name "cf-infra-bot"
    git remote add http https://github.com/cloudfoundry/bosh-bootloader.git
    git fetch http

    git checkout master

    git merge --no-edit bump-deployments-ci

    cp -r . ${ROOT}/bosh-bootloader
  popd > /dev/null
}

main
