#!/bin/bash -exu

pushd terraforming-aws > /dev/null

  terraform init

  export TF_VAR_env_name=terraforming-aws-env
  set +x
    export TF_VAR_access_key=${AWS_ACCESS_KEY_ID}
    export TF_VAR_secret_key=${AWS_SECRET_ACCESS_KEY}
  set -x
  export TF_VAR_region=us-west-1
  export TF_VAR_availability_zones='["us-west-1a"]'
  export TF_VAR_ops_manager_ami=some-ami
  export TF_VAR_rds_instance_count=1
  export TF_VAR_dns_suffix=terraforming-aws-env.example.com

  terraform plan

popd > /dev/null
