#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  rm -rf "${root_dir}/etcd-release/blobs/etcd"
  bosh sync-blobs --dir="${root_dir}/etcd-release"
  local etcd_binary
  etcd_binary="$(tar tzf "${root_dir}"/etcd-release/blobs/etcd/etcd-*.tar.gz | grep etcd$)"
  tar zxf "${root_dir}"/etcd-release/blobs/etcd/etcd-*.tar.gz -C /tmp "$etcd_binary"

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry-incubator"
  pushd "${GOPATH}/src/github.com/cloudfoundry-incubator" > /dev/null
    ln -s "${root_dir}/etcd-release/src/etcd-metrics-server"
    pushd ./etcd-metrics-server > /dev/null
      export GOPATH="${PWD}/Godeps/_workspace:${GOPATH}"
      export PATH="${PWD}/Godeps/_workspace/bin:${PATH}"

      mkdir -p "${PWD}/Godeps/_workspace/bin"
      mv "/tmp/$etcd_binary" "${PWD}/Godeps/_workspace/bin/"

      ginkgo -r -race -randomizeAllSpecs -randomizeSuites
    popd > /dev/null

  popd > /dev/null
}

main "${PWD}"
