#!/bin/bash -exu

ROOT="${PWD}"
CURRENT_TIME=$(date +%s)

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  ./bosh-bootloader/scripts/acceptance_tests aws
popd > /dev/null
