#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/genevievelesperance"

pushd "${GOPATH}/src/github.com/genevievelesperance" > /dev/null
  ln -s "${ROOT}/leftovers"
  ./leftovers/scripts/test
popd > /dev/null
