#!/bin/bash -exu

export BBL_IAAS="aws"

function check_fast_fails() {
  set +x
  if [ -z "${BBL_AWS_ACCESS_KEY_ID}" ]; then
    echo "\$BBL_AWS_ACCESS_KEY_ID is a required parameter for AWS."
    exit 1
  fi

  if [ -z "${BBL_AWS_SECRET_ACCESS_KEY}" ]; then
    echo "\$BBL_AWS_SECRET_ACCESS_KEY is a required parameter for AWS."
    exit 1
  fi

  if [ -z "${BBL_AWS_REGION}" ]; then
    echo "\$BBL_AWS_REGION is a required parameter for AWS."
    exit 1
  fi

  if [ -z "${BBL_STATE_DIR}" ]; then
    echo "\$BBL_STATE_DIR is a required parameter for AWS."
    exit 1
  fi

  if [ -z "${BBL_NAME}" ]; then
    echo "\$BBL_NAME is a required parameter for AWS."
    exit 1
  fi

  if [ -n "${BBL_LB_DOMAIN}" ]; then
    if [ -z "${BBL_LB_CERT}" ]; then
      echo "\$BBL_LB_CERT is a required parameter for AWS when creating LBs."
      exit 1
    fi

    if [ -z "${BBL_LB_KEY}" ]; then
      echo "\$BBL_LB_KEY is a required parameter for AWS when creating LBs."
      exit 1
    fi
  fi
  set -x
}


function create_or_update_lbs() {
  local bbl_lb_key_path
  bbl_lb_key_path="/tmp/bbl_lb_key"

  local bbl_lb_cert_path
  bbl_lb_cert_path="/tmp/bbl_lb_cert"

  set +x
  echo "${BBL_LB_CERT}" > "${bbl_lb_cert_path}"
  echo "${BBL_LB_KEY}" > "${bbl_lb_key_path}" set -x

  bbl \
    --debug \
    --state-dir "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}" \
    create-lbs \
      --type cf \
      --cert "${bbl_lb_cert_path}" \
      --key "${bbl_lb_key_path}" \
      --skip-if-exists \
      --domain "${BBL_LB_DOMAIN}" > bbl_create_lbs.log

  bbl \
    --debug \
    --state-dir "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}" \
    update-lbs \
      --cert "${bbl_lb_cert_path}" \
      --key "${bbl_lb_key_path}" \
      --domain "${BBL_LB_DOMAIN}" > bbl_update_lbs.log
}

function commit_bbl_state_file() {
  local root_dir
  root_dir="${1}"

  pushd "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}" > /dev/null
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CI Infra Bot"
      git config user.email "cf-infrastructure@pivotal.io"
      git add bbl-state.json
      git commit -m "Update ${BBL_NAME} bbl-state.json"
    fi
  popd > /dev/null

  pushd "${root_dir}"
    shopt -s dotglob
    cp -R bbl-states-repo/* bbl-states-repo-out/
  popd
}

function write_ops_file_to_bump_compilation_workers() {
  local root_dir
  root_dir="${1}"

  local ops_file_path
  ops_file_path="${root_dir}/director_ops"

  cat > "${ops_file_path}" <<EOT
---
- type: replace
  path: /instance_groups/name=bosh/properties/director/workers
  value: 7
EOT

  echo "${ops_file_path}"
}

function main() {
  local root_dir
  root_dir="${1}"

  check_fast_fails

  local ops_file_path
  ops_file_path=$(write_ops_file_to_bump_compilation_workers "${root_dir}")

  mkdir -p "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}"
  bbl \
    --debug \
    --state-dir "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}" \
    up \
      --name ${BBL_NAME} \
      --ops-file "${ops_file_path}" > bbl_up.log

  if [ -n "${BBL_LB_DOMAIN}" ]; then
    create_or_update_lbs
  fi
}

trap "commit_bbl_state_file ${PWD}" EXIT

main ${PWD}
