#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  export CONCOURSE_DEPLOYMENT_PATH="${ROOT}/concourse-deployment"
  export CONCOURSE_RELEASE_PATH="${ROOT}/concourse-release/release.tgz"
  export GARDEN_RELEASE_PATH="${ROOT}/garden-release/release.tgz"
  export STEMCELL_PATH="${ROOT}/stemcell/stemcell.tgz"
  export STEMCELL_VERSION="$(cat ${ROOT}/stemcell/version)"
  ./bosh-bootloader/scripts/concourse_acceptance_tests
popd > /dev/null
