#!/bin/bash -exu

ROOT="${PWD}"
release_version="99999+dev.$(date +%s)"

function upload_release() {
  local release_path="$1"

  pushd "${ROOT}/${release_path}" > /dev/null
    bosh -n create-release --force --version ${release_version}
    bosh -n upload-release --rebase
  popd > /dev/null
}

function deploy_etcd() {
  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"
  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/infrastructure-ci"
    pushd ./infrastructure-ci/scripts/common/deploy-aws-manifests > /dev/null
      set +x
      go run main.go \
        --manifest-path "${ROOT}/release/${MANIFEST_PATH}" \
        --director "https://${BOSH_ENVIRONMENT}:25555" \
        --user "${BOSH_CLIENT}" \
        --password "${BOSH_CLIENT_SECRET}" \
        --aws-access-key-id "${AWS_ACCESS_KEY_ID}" \
        --aws-secret-access-key "${AWS_SECRET_ACCESS_KEY}" \
        --aws-region "${AWS_DEFAULT_REGION}"
      set -x
    popd > /dev/null
  popd > /dev/null
}

function main() {
  upload_release "consul-release"
  upload_release "release"
  deploy_etcd
}

function teardown() {
  set +e
  bosh -n delete-release consul/${release_version}
  bosh -n delete-release etcd/${release_version}
  set -e
}

trap teardown EXIT

main
