---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
- name: dockerfiles
- name: golang-linux

outputs:
- name: docker-workspace

params:
  DOCKERFILE:

run:
  path: /bin/bash
  args:
  - -c
  - |
    cp "./dockerfiles/${DOCKERFILE}" docker-workspace/
    tar -C docker-workspace -xzf golang-linux/go*.linux-amd64.tar.gz
