#!/bin/bash -exu

export ROOT="${PWD}"
export CONSUL_RELEASE_VERSION="99999+dev.$(date +%s)"
export STEMCELL_VERSION="$(cat ${ROOT}/stemcell/version)"
export TURBULENCE_RELEASE_VERSION="$(cat ${ROOT}/turbulence-release/version)"
export LATEST_CONSUL_RELEASE_VERSION="$(cat ${ROOT}/latest-consul-release/version)"

function main() {
  setup_bosh_env_vars

  upload_stemcell
  if $WINDOWS_CLIENTS; then
    upload_windows_stemcell
  fi

  upload_releases
  generate_manifest
  force_compilation

  /usr/local/bin/bosh deployment "${ROOT}/consats.yml"
  /usr/local/bin/bosh -n deploy
  /usr/local/bin/bosh run-errand acceptance-tests

  cleanup_deployment "consul"
  cleanup_deployment "turbulence-consul"

  /usr/local/bin/bosh -n clean-up
}

function setup_bosh_env_vars() {
  set +x
  pushd "${ROOT}/bbl-states-repo/${BBL_STATE_DIR}" > /dev/null
    export BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT_SECRET=$(bbl director-password)
  popd > /dev/null
  set -x
}

function upload_stemcell() {
  pushd "${ROOT}/stemcell" > /dev/null
    /usr/local/bin/bosh upload-stemcell stemcell.tgz
  popd > /dev/null
}

function upload_windows_stemcell() {
  pushd "${ROOT}/windows-stemcell" > /dev/null
    /usr/local/bin/bosh upload-stemcell light-bosh-stemcell-*-google-kvm-windows2012R2-go_agent.tgz
  popd > /dev/null
}

function upload_releases() {
  pushd "${ROOT}/turbulence-release" > /dev/null
    /usr/local/bin/bosh upload-release release.tgz
  popd > /dev/null

  pushd "${ROOT}/consul-release" > /dev/null
    /usr/local/bin/bosh -n create-release --force --version "${CONSUL_RELEASE_VERSION}"
    /usr/local/bin/bosh upload-release
  popd > /dev/null

  pushd "${ROOT}/latest-consul-release" > /dev/null
    /usr/local/bin/bosh upload-release release.tgz
  popd > /dev/null
}

function force_compilation() {
  pushd /tmp > /dev/null
    sed  -e "s/CONSUL_RELEASE_VERSION/${CONSUL_RELEASE_VERSION}/g" \
      -e "s/TURBULENCE_RELEASE_VERSION/${TURBULENCE_RELEASE_VERSION}/g" \
      -e "s/STEMCELL_VERSION/${STEMCELL_VERSION}/g" \
      "${ROOT}/ci/scripts/run-consats/fixtures/consul_compilation.yml" > "consul_compilation.yml"

    /usr/local/bin/bosh -d "consul_compilation.yml" -n deploy
    /usr/local/bin/bosh -d "consul_compilation.yml" export-release "consul/${CONSUL_RELEASE_VERSION}" "ubuntu-trusty/${STEMCELL_VERSION}"
    /usr/local/bin/bosh -d "consul_compilation.yml" export-release "turbulence/${TURBULENCE_RELEASE_VERSION}" "ubuntu-trusty/${STEMCELL_VERSION}"
    /usr/local/bin/bosh -d "consul_compilation.yml" -n delete-deployment
  popd > /dev/null
}

function generate_manifest() {
  mkdir -p "${ROOT}/consul-release/aws"
  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${ROOT}/ci" "infrastructure-ci"

    pushd "${GOPATH}/src/github.com/cloudfoundry/infrastructure-ci" > /dev/null
      GO15VENDOREXPERIMENT=1 go run \
        "./scripts/run-consats/generate_manifest.go" \
        "${ROOT}/consul-release/manifests/consats.yml" \
        > "${ROOT}/consats.yml"
    popd > /dev/null
  popd > /dev/null
}

function cleanup_deployment() {
  local deployment
  deployment="${1}-[A-Za-z0-9]\{8\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{4\}-[A-Za-z0-9]\{12\}"

  for i in $(/usr/local/bin/bosh deployments | grep -o "${deployment}" | uniq); do
    /usr/local/bin/bosh -d $i -n delete-deployment
  done

  test -z "$(/usr/local/bin/bosh deployments | grep "${deployment}")"
}

function teardown() {
  set +e
  /usr/local/bin/bosh -d consats -n delete-deployment
  /usr/local/bin/bosh -n delete-release consul
  set -e
}

trap teardown EXIT

main
