#!/bin/bash -exu

cwd=${PWD}

pushd product
  version="$(unzip -p *.pivotal 'metadata/*.yml' | grep '^product_version:' | cut -d" " -f2 | sed 's/"//g')"
popd

product="$(ls -1 "${cwd}"/product/*.pivotal)"
stemcell="$(ls -1 "${cwd}"/stemcell/*.tgz)"
opsman_dns=$(jq -r .ops_manager_dns < "${cwd}/env-state/metadata")
export ENV_NAME="$(cat env-state/name)"


# generate-config
texplate execute "${PRODUCT_CONFIG_TEMPLATE}" -f "${cwd}/env-state/metadata" -o yaml > "${cwd}/product-config.yml"

# upload and stage product
om -t "https://${opsman_dns}" -k upload-stemcell --stemcell "${stemcell}"
om -t "https://${opsman_dns}" -k upload-product --product "${product}"
om -t "https://${opsman_dns}" -k stage-product --product-name "${PRODUCT_NAME}" --product-version "${version}"

# configure-product
om -t "https://${opsman_dns}" -k configure-product -n "${PRODUCT_NAME}" --config "${cwd}/product-config.yml"
