#!/bin/bash -exu

cwd=${PWD}
configure_om_dir="${PWD}/ci/scripts/terraforming/configure-om"

terraform output -state "${cwd}/terraform-state-gcp/terraform.tfstate" --json | \
  jq '[. | to_entries[] | {"key": .key, "value": .value.value}] | from_entries' \
  > "${cwd}/tfoutput.json"

opsman_dns=$(jq -r .ops_manager_dns < "${cwd}/tfoutput.json")
texplate execute "${configure_om_dir}/config-director-template.yml" -f "${cwd}/tfoutput.json" -o yaml > "${cwd}/director-config.yml"
texplate execute "${configure_om_dir}/config-product-template.yml" -f "${cwd}/tfoutput.json" -o yaml > "${cwd}/product-config.yml"

om -t "https://${opsman_dns}" -k configure-director --config "${cwd}/director-config.yml"
om -t "https://${opsman_dns}" -k configure-product --config "${cwd}/product-config.yml"

om -t "https://${opsman_dns}" -k apply-changes
