#!/bin/bash -exu

  set +x
    cat > config.yml <<-EOF
		opsman-configuration:
		  vsphere:
		    vcenter:
		      url: "${OPS_VCENTER_URL}"
		      username: "${OPS_VCENTER_USERNAME}"
		      password: "${OPS_VCENTER_PASSWORD}"
		      datastore: "${OPS_VCENTER_DATASTORE}"
		      datacenter: "${OPS_VCENTER_DATACENTER}"
		      insecure: "${OPS_VCENTER_INSECURE}"
		      ca_cert: "${OPS_VCENTER_CA_CERT}"
		      resource_pool: "${OPS_VCENTER_RESOURCE_POOL}"
		      # host: https://vcsa-01.haas-401.pez.pivotal.io
		      # folder: /datacenter/vm/folder
		    disk_type: "${OPS_DISKTYPE}"
		    private_ip: "${OPS_PRIVATE_IP}"
		    dns: "${OPS_DNS}"
		    ntp: "${OPS_NTP}"
		    ssh_password: "${OPS_SSH_PASSWORD}"
		    hostname: "${OPS_HOSTNAME}"
		    network: "${OPS_NETWORK}"
		    netmask: "${OPS_NETMASK}"
		    gateway: "${OPS_GATEWAY}"
		    vm_name: "${OPS_VM_NAME}"
		    memory: "${OPS_VM_MEMORY}"
		    cpu: "${OPS_VM_CPU}"
EOF
  set -x

  cat config.yml
