#!/bin/bash -exu

ROOT="${PWD}"

terraform_version="$(cat terraform/version)"
terraform_url="https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip"

wget "${terraform_url}"
unzip "$(basename ${terraform_url})" -d /tmp
chmod +x /tmp/terraform
mv /tmp/terraform /usr/local/bin/terraform

terraform version

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  ./bosh-bootloader/scripts/acceptance_tests gcp
popd > /dev/null
