#!/bin/bash -exu

ROOT="${PWD}"

terraform_version="$(cat terraform/version)"
terraform_url="https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip"

wget "${terraform_url}"
unzip "$(basename ${terraform_url})" -d /tmp
chmod +x /tmp/terraform
mv /tmp/terraform /usr/local/bin/terraform

terraform version

cp /tmp/terraform ${ROOT}/bosh-bootloader/terraform/binary_dist/terraform

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  export TF_LOG=DEBUG
  export TF_LOG_PATH="${ROOT}/tf-logs.txt"
  export BOSH_LOG_LEVEL=debug
  export BOSH_LOG_PATH="${ROOT}/bosh-logs/bosh-logs.txt"

  ./bosh-bootloader/scripts/acceptance_tests bbl
popd > /dev/null
