groups:
- name: az-automation
  jobs:
  - test
  - build-release
  - bump-brew-tap

resources:
- name: az-automation
  type: git
  source:
    branch: master
    uri: https://github.com/genevievelesperance/az-automation.git

- name: release
  type: github-release
  source:
    owner: genevievelesperance
    repository: az-automation
    access_token: {{cf_infra_bot_user_github_access_token}}
    drafts: false

- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: homebrew-tap
  type: git
  source:
    branch: master
    uri: https://github.com/genevievelesperance/homebrew-tap.git

jobs:
- name: test
  plan:
  - aggregate:
    - get: ci
    - get: az-automation
      trigger: true
  - task: test
    file: ci/scripts/az-automation/test/task.yml

- name: build-release
  plan:
  - aggregate:
    - get: ci
    - get: release
    - get: az-automation
      passed: [test]
  - task: build-release
    file: ci/scripts/az-automation/build-release/task.yml
  - put: release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/az-automation-*

- name: bump-brew-tap
  plan:
    - aggregate:
      - get: homebrew-tap
      - get: release
        params:
          version: { tag: release/version }
          globs:
          - az-automation-*_osx
          - az-automation-*_linux_x86-64
      - get: ci
    - task: bump-brew-tap
      file: ci/scripts/az-automation/bump-brew-tap/task.yml
    - put: homebrew-tap
      params:
        repository: updated-homebrew-tap/homebrew-tap
