groups:
- name: az-automation
  jobs:
  - tests
  - build-release

resources:
- name: az-automation
  type: git
  source:
    branch: master
    uri: https://github.com/genevievelesperance/az-automation.git

- name: az-automation-release
  type: github-release
  source:
    owner: genevievelesperance
    repository: az-automation
    access_token: {{cf_infra_bot_user_github_access_token}}
    drafts: false

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

jobs:
- name: tests
  plan:
  - aggregate:
    - get: infrastructure-ci
    - get: az-automation
      trigger: true
  - task: test
    file: infrastructure-ci/scripts/az-automation/test/task.yml

- name: build-release 
  plan:
  - aggregate:
    - get: infrastructure-ci
    - get: version
      resource: az-automation-release
    - get: az-automation
  - task: test
    file: infrastructure-ci/scripts/az-automation/build-release/task.yml
