groups:
- name: az-automation
  jobs:
  - test
  - build-release
  - bump-brew-tap

resources:
- name: az-automation
  type: git
  source:
    branch: master
    uri: https://github.com/genevieve/az-automation.git

- name: release
  type: github-release
  source:
    owner: genevieve
    repository: az-automation
    access_token: ((cf_infra_bot_user_github_access_token))

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: homebrew-tap
  type: git
  source:
    branch: master
    uri: git@github.com:genevieve/homebrew-tap.git
    private_key: ((cf_infra_bot_github_user.private_key))

jobs:
- name: test
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: az-automation
      trigger: true
  - task: test
    file: ci/scripts/az-automation/test/task.yml

- name: build-release
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release
    - get: az-automation
      passed: [test]
  - task: build-release-with-minor-bump
    file: ci/scripts/az-automation/build-release/task.yml
  - put: release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/az-automation-*

- name: bump-brew-tap
  plan:
  - aggregate:
    - get: az-automation
      passed: [build-release]
    - get: homebrew-tap
    - get: release
      params:
        version: { tag: release/version }
        globs:
        - az-automation-*-darwin-amd64
        - az-automation-*-linux-amd64
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: bump-brew-tap
    file: ci/scripts/az-automation/bump-brew-tap/task.yml
  - put: homebrew-tap
    params:
      repository: updated-homebrew-tap/homebrew-tap
