groups:
- name: bbl-latest
  jobs:
  - unit-tests
  - deploy-app

resources:
- name: bbl-latest-app
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
    paths:
    - apps/bbl-latest
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: pws
  type: cf
  source:
    api: https://api.run.pivotal.io
    client_id: ((pcf_infra_prod_service_account.username))
    client_secret: ((pcf_infra_prod_service_account.password))
    organization: ((pws_organization))
    space: ((pws_space))

jobs:
- name: unit-tests
  public: true
  plan:
  - aggregate:
    - get: bbl-latest-app
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: test
    file: ci/scripts/misc/bbl-latest/unit-tests/task.yml
    params:
      GITHUB_OAUTH_TOKEN: ((github_oauth_token))
- name: deploy-app
  public: true
  plan:
  - get: bbl-latest-app
    passed: [unit-tests]
    trigger: true
  - put: pws
    params:
      manifest: bbl-latest-app/apps/bbl-latest/manifest.yml
