groups:
- name: bosh-deployment
  jobs:
  - bump-deployments
  - test-bosh-bootloader
  - aws-acceptance-tests
  - gcp-acceptance-tests
  - github-release
  - merge-bump-deployments-change

resource_types:
- name: latest-git-resource
  type: docker-image
  source:
    repository: concourse/git-resource
    tag: latest

resources:
- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: jumpbox-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cppforlife/jumpbox-deployment.git

- name: bosh-bootloader
  type: latest-git-resource
  source:
    branch: master
    uri: git@github.com:cloudfoundry/bosh-bootloader.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: bosh-bootloader-bump-deployments-ci
  type: git
  source:
    branch: bump-deployments-ci
    uri: git@github.com:cloudfoundry/bosh-bootloader.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: bbl-release
  type: github-release
  source:
    user: cloudfoundry
    repository: bosh-bootloader
    access_token: {{cf_infra_bot_user_github_access_token}}

jobs:
- name: bump-deployments
  serial: true
  serial_groups: [aws,gcp]
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
    - get: bbl-release
    - get: bosh-deployment
      trigger: true
    - get: jumpbox-deployment
      trigger: true
  - task: bump-deployments
    file: ci/scripts/bosh-deployment/bump-deployments/task.yml
  - put: bump-deployments-ci
    resource: bosh-bootloader-bump-deployments-ci
    params:
      repository: bump-deployments-ci
      force: true

- name: test-bosh-bootloader
  serial: true
  serial_groups: [aws,gcp]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      passed: [bump-deployments]
      trigger: true
  - task: test
    file: ci/scripts/bosh-bootloader/test-bosh-bootloader/task.yml

- name: aws-acceptance-tests
  serial: true
  serial_groups: [aws]
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - aggregate:
    - task: bbl-plan
      file: ci/scripts/bosh-bootloader/acceptance/task.yml
      params:
        BBL_IAAS: aws
        BBL_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        BBL_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        BBL_AWS_REGION: {{aws_region}}
        BBL_TEST_ENV_ID_PREFIX: bump-deployments
        BBL_TEST_PACKAGES: bbl
        RUN_TEST: plan
    - task: latest-error
      file: ci/scripts/bosh-bootloader/acceptance/task.yml
      params:
        BBL_IAAS: aws
        BBL_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        BBL_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        BBL_AWS_REGION: {{aws_region}}
        BBL_TEST_ENV_ID_PREFIX: bump-deployments
        BBL_TEST_PACKAGES: bbl
        RUN_TEST: latest-error
    - task: bbl-up
      file: ci/scripts/bosh-bootloader/acceptance/task.yml
      params:
        BBL_IAAS: aws
        BBL_AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
        BBL_AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
        BBL_AWS_REGION: {{aws_region}}
        BBL_TEST_ENV_ID_PREFIX: bump-deployments
        BBL_TEST_PACKAGES: bbl
        RUN_TEST: bbl-up

- name: gcp-acceptance-tests
  serial: true
  serial_groups: [gcp]
  plan:
  - aggregate:
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      passed: [test-bosh-bootloader]
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - aggregate:
    - task: gcp-tests
      file: ci/scripts/bosh-bootloader/acceptance/task.yml
      params:
        BBL_IAAS: gcp
        BBL_GCP_SERVICE_ACCOUNT_KEY: {{bbl_gcp_service_account_key}}
        BBL_GCP_PROJECT_ID: {{bbl_gcp_project_id}}
        BBL_GCP_REGION: {{bbl_gcp_region}}
        BBL_GCP_ZONE: {{bbl_gcp_zone}}
        BBL_TEST_ENV_ID_PREFIX: bump-deployments
        BBL_TEST_PACKAGES: bbl

- name: github-release
  serial: true
  serial_groups: [aws,gcp]
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-release
    - get: bosh-bootloader
      resource: bosh-bootloader-bump-deployments-ci
      passed: [aws-acceptance-tests, gcp-acceptance-tests]
      trigger: true
  - task: bump-version
    file: ci/scripts/bosh-deployment/bump-version/task.yml
  - task: build-binaries
    file: ci/scripts/bosh-bootloader/build-final-release/task.yml
    params:
      BUMP_DEPLOYMENTS: true
  - put: bbl-release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      body: builds/body
      globs:
      - builds/bin/bbl-*

- name: merge-bump-deployments-change
  serial: true
  serial_groups: [aws,gcp]
  public: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bosh-bootloader-bumped
      resource: bosh-bootloader-bump-deployments-ci
      passed: [github-release]
      trigger: true
  - task: merge-bosh-deployment-change
    file: ci/scripts/bosh-deployment/commit-bosh-deployment-change/task.yml
  - put: bosh-bootloader
    params:
      repository: bosh-bootloader
