---
resources:
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: infrastructure-ci-bbl-states
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git
    private_key: ((cf_infra_bot_github_user.private_key))

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment-concourse-tasks
    private_key: ((cf_infra_bot_github_user.private_key))
    tag: v8.0

- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

jobs:
- name: bbl-up-concourse
  build_logs_to_retain: 101
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: infrastructure-ci-bbl-states
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment-concourse-tasks-image
  - task: up
    image: cf-deployment-concourse-tasks-image
    file: ci/scripts/bosh-bootloader/bbl-up-concourse/task.yml
    input_mapping:
      bbl-state: infrastructure-ci-bbl-states
    params:
      BBL_IAAS: gcp
      BBL_GCP_REGION: us-east1
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((infrastructure_ci_gcp_service_account_key))
      BBL_STATE_DIR: infra-ci
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: updated-bbl-state
        rebase: true
  - task: delete-bosh-dns
    file: ci/scripts/misc/delete-bosh-dns/task.yml
    input_mapping:
      bbl-state: infrastructure-ci-bbl-states
    params:
      BBL_STATE_DIR: infra-ci
    image: cf-deployment-concourse-tasks-image
