---
resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: infrastructure-ci-bbl-states
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: concourse-deployment
  type: git
  source:
    branch: v4.0.0
    uri: https://github.com/concourse/concourse-bosh-deployment.git

- name: concourse-secrets
  type: s3
  source:
    bucket: infra-concourse-secrets
    versioned_file: concourse-secrets.yml
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    region_name: us-west-2

- name: prod-concourse-vars
  type: s3
  source:
    bucket: infra-concourse-secrets
    versioned_file: prod-concourse-vars.yml
    access_key_id: {{aws_access_key_id}}
    secret_access_key: {{aws_secret_access_key}}
    region_name: us-west-2

- name: ubuntu-xenial-stemcell-gcp
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent

- name: ubuntu-xenial-stemcell-vsphere
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-xenial-go_agent

- name: concourse-bosh-deployment
  type: bosh-deployment
  source:
    deployment: concourse

jobs:
- name: update-concourse-gcp
  interruptible: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: infrastructure-ci-bbl-states
    - get: concourse-deployment
    - get: concourse-secrets
    - get: ubuntu-xenial-stemcell-gcp
    - get: prod-concourse-vars
  - task: create-bosh-source-file
    file: ci/scripts/bosh-bootloader/create-bosh-deployment-source-file/task.yml
    params:
      BBL_STATE_DIR: infra-ci
    input_mapping:
      bbl-states: infrastructure-ci-bbl-states
  - put: concourse-bosh-deployment
    params:
      source_file: source-file/bosh-source.json
      manifest: concourse-deployment/cluster/concourse.yml
      stemcells: [ ubuntu-xenial-stemcell-gcp/stemcell.tgz ]
      vars_files:
        - concourse-deployment/versions.yml
        - concourse-secrets/concourse-secrets.yml
        - prod-concourse-vars/prod-concourse-vars.yml
      ops_files:
        - concourse-deployment/cluster/operations/privileged-https.yml
        - concourse-deployment/cluster/operations/privileged-http.yml
        - concourse-deployment/cluster/operations/github-auth.yml
        - concourse-deployment/cluster/operations/tls.yml
        - concourse-deployment/cluster/operations/web-network-extension.yml
        - concourse-deployment/cluster/operations/worker-ephemeral-disk.yml
        - concourse-deployment/cluster/operations/scale.yml

- name: update-concourse-vsphere-worker
  interruptible: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
      tags:
      - {{vsphere_network_name}}
    - get: infrastructure-ci-bbl-states
      tags:
      - {{vsphere_network_name}}
    - get: concourse-deployment
      tags:
      - {{vsphere_network_name}}
    - get: concourse-secrets
      tags:
      - {{vsphere_network_name}}
    - get: ubuntu-xenial-stemcell-vsphere
      tags:
      - {{vsphere_network_name}}
    - get: prod-concourse-vars
      tags:
      - {{vsphere_network_name}}
  - task: create-bosh-source-file
    file: ci/scripts/bosh-bootloader/create-bosh-deployment-source-file/task.yml
    tags:
    - {{vsphere_network_name}}
    params:
      BBL_STATE_DIR: vsphere-concourse
    input_mapping:
      bbl-states: infrastructure-ci-bbl-states
  - put: concourse-bosh-deployment
    tags:
    - {{vsphere_network_name}}
    params:
      source_file: source-file/bosh-source.json
      manifest: concourse-deployment/cluster/external-worker.yml
      stemcells: [ ubuntu-xenial-stemcell-vsphere/stemcell.tgz ]
      vars_files:
        - concourse-deployment/versions.yml
        - concourse-secrets/concourse-secrets.yml
        - prod-concourse-vars/prod-concourse-vars.yml
