---
groups:
- name: consul
  jobs:
  - check-git-submodules
  - deploy-sample-manifest
  - merge-master-into-develop
  - deploy-cf
  - create-final-release

resources:
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: infrastructure-ci-bbl-states
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git
    private_key: ((cf_infra_bot_github_user.private_key))

- name: cf-deployment-concourse-tasks-docker-image
  type: docker-image
  source:
    tag: v5.14.0
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

- name: cf-deployment
  type: git
  source:
    branch: master
    tag_filter: v2.9.*
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git

- name: consul-release-master
  type: git
  source:
    branch: master
    private_key: ((cf_infra_bot_github_user.private_key))
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: consul-release-gh
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: consul-release
    access_token: ((cf_infra_bot_user_github_access_token))

- name: consul-release-merge-target
  type: git
  source:
    branch: develop
    private_key: ((cf_infra_bot_github_user.private_key))
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    tag_filter: v6.14
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: ((oss-s3-buckets-stack-private-key.private_key))
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

jobs:
- name: check-git-submodules
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: repo
      resource: consul-release-develop
      trigger: true
  - task: check-git-submodules
    file: ci/scripts/common/check-git-submodules/task.yml

- name: deploy-sample-manifest
  plan:
  - aggregate:
    - get: release
      resource: consul-release-develop
      passed:
      - check-git-submodules
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: bosh-deployment
    - get: gcp-stemcell
  - task: deploy-sample-manifest
    file: ci/scripts/common/deploy-sample-manifests/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp_service_account_key))
      BBL_GCP_PROJECT_ID: ((gcp_project_id))
      BBL_GCP_REGION: ((gcp_region))
      BBL_GCP_ZONE: ((gcp_zone))
      CLOUD_CONFIG: manifests/cloud_config.yml
      MANIFESTS: manifests/multi-az-with-ssl.yml

- name: deploy-cf
  serial: true
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: infrastructure-ci-bbl-states
    - get: cf-deployment-concourse-tasks-docker-image
    - get: ci
      resource: infrastructure-ci
    - get: cf-deployment
    - get: ops-files
      resource: cf-deployment
    - get: vars-files
      resource: infrastructure-ci-bbl-states
    - get: vars-store
      resource: infrastructure-ci-bbl-states
    - get: release
      resource: consul-release-develop
      trigger: true
      passed: [deploy-sample-manifest]
  - task: bbl-leftovers
    file: ci/scripts/bosh-bootloader/leftovers/task.yml
    image: cf-deployment-concourse-tasks-docker-image
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      BBL_GCP_REGION: ((gcp_region))
      BBL_ENV_NAME: cf-with-consul
      BBL_STATE_DIR: cf-with-consul
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    image: cf-deployment-concourse-tasks-docker-image
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      BBL_GCP_REGION: ((gcp_region))
      BBL_LB_CERT: ((cf_with_consul_lb_cert.certificate))
      BBL_LB_KEY: ((cf_with_consul_lb_cert.private_key))
      LB_DOMAIN: cf-with-consul.infrastructure.cf-app.com
      BBL_ENV_NAME: cf-with-consul
      BBL_STATE_DIR: cf-with-consul
      GIT_COMMIT_EMAIL: cf-infrastructure@pivotal.io
      GIT_COMMIT_USERNAME: CI Infra Bot
    input_mapping:
      bbl-state: infrastructure-ci-bbl-states
      bbl-config: infrastructure-ci-bbl-states
    on_failure:
      task: bbl-up-destroy-infrastructure
      file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
      image: cf-deployment-concourse-tasks-docker-image
      params:
        BBL_STATE_DIR: cf-with-consul
        BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      input_mapping:
        bbl-state: updated-bbl-state
      ensure:
        put: infrastructure-ci-bbl-states
        params:
          rebase: true
          repository: updated-bbl-state
  - task: add-to-gcp-dns
    file: ci/scripts/common/manage-gcp-dns/task.yml
    params:
      BBL_STATE_DIR: cf-with-consul
      GCP_DNS_PROJECT_ID: ((cf_infra_gcp_project_id))
      GCP_DNS_SERVICE_ACCOUNT_EMAIL: ((cf_infra_gcp_service_account_email))
      GCP_DNS_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      GCP_DNS_ZONE_NAME: infrastructure
      GCP_DNS_RECORD_SET_NAME: cf-with-consul.infrastructure.cf-app.com
      ACTION: add
    input_mapping:
      bbl-states-repo: updated-bbl-state
    on_failure:
      task: destroy-infrastructure
      file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
      image: cf-deployment-concourse-tasks-docker-image
      input_mapping:
        bbl-state: updated-bbl-state
      params:
        BBL_STATE_DIR: cf-with-consul
        BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      ensure:
        put: infrastructure-ci-bbl-states
        params:
          rebase: true
          repository: updated-bbl-state
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    image: cf-deployment-concourse-tasks-docker-image
    input_mapping:
      bbl-state: updated-bbl-state
    params:
      BBL_STATE_DIR: cf-with-consul
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      INFRASTRUCTURE: google
    on_failure:
      do:
      - task: remove-from-gcp-dns
        file: ci/scripts/common/manage-gcp-dns/task.yml
        params:
          BBL_STATE_DIR: cf-with-consul
          GCP_DNS_PROJECT_ID: ((cf_infra_gcp_project_id))
          GCP_DNS_SERVICE_ACCOUNT_EMAIL: ((cf_infra_gcp_service_account_email))
          GCP_DNS_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
          GCP_DNS_ZONE_NAME: infrastructure
          GCP_DNS_RECORD_SET_NAME: cf-with-consul.infrastructure.cf-app.com
          ACTION: remove
        input_mapping:
          bbl-states-repo: updated-bbl-state
      - task: destroy-infrastructure
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_STATE_DIR: cf-with-consul
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
        ensure:
          put: infrastructure-ci-bbl-states
          params:
            rebase: true
            repository: updated-bbl-state
  - task: deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    image: cf-deployment-concourse-tasks-docker-image
    input_mapping:
      bbl-state: updated-bbl-state
    params:
      BBL_STATE_DIR: cf-with-consul
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      SYSTEM_DOMAIN: cf-with-consul.infrastructure.cf-app.com
      VARS_STORE_FILE: cf-with-consul/deployment-vars.yml
      OPS_FILES: "operations/use-compiled-releases.yml operations/scale-to-one-az.yml operations/experimental/fast-deploy-with-downtime-and-danger.yml"
    on_failure:
      do:
      - task: remove-from-gcp-dns
        file: ci/scripts/common/manage-gcp-dns/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        params:
          BBL_STATE_DIR: cf-with-consul
          GCP_DNS_PROJECT_ID: ((cf_infra_gcp_project_id))
          GCP_DNS_SERVICE_ACCOUNT_EMAIL: ((cf_infra_gcp_service_account_email))
          GCP_DNS_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
          GCP_DNS_ZONE_NAME: infrastructure
          GCP_DNS_RECORD_SET_NAME: cf-with-consul.infrastructure.cf-app.com
          ACTION: remove
        input_mapping:
          bbl-states-repo: updated-bbl-state
      - task: delete-cf-deployment
        file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_STATE_DIR: cf-with-consul
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      - task: bosh-cleanup
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          CLEAN_ALL: true
          BBL_STATE_DIR: cf-with-consul
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      - task: destroy-infrastructure
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_STATE_DIR: cf-with-consul
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
        ensure:
          put: infrastructure-ci-bbl-states
          params:
            rebase: true
            repository: updated-bbl-state
  - task: smoke-tests
    image: cf-deployment-concourse-tasks-docker-image
    input_mapping:
      bbl-state: updated-bbl-state
    config:
      platform: linux
      inputs:
      - name: bbl-state
      run:
        path: bash
        args:
          - "-c"
          - "cd bbl-state/cf-with-consul/ && eval \"$(bbl print-env)\" && bosh -d cf run-errand smoke-tests"
    ensure:
      do:
      - task: remove-from-gcp-dns
        file: ci/scripts/common/manage-gcp-dns/task.yml
        params:
          BBL_STATE_DIR: cf-with-consul
          GCP_DNS_PROJECT_ID: ((cf_infra_gcp_project_id))
          GCP_DNS_SERVICE_ACCOUNT_EMAIL: ((cf_infra_gcp_service_account_email))
          GCP_DNS_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
          GCP_DNS_ZONE_NAME: infrastructure
          GCP_DNS_RECORD_SET_NAME: cf-with-consul.infrastructure.cf-app.com
          ACTION: remove
        input_mapping:
          bbl-states-repo: updated-bbl-state
      - task: delete-cf-deployment
        file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_STATE_DIR: cf-with-consul
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      - task: bosh-cleanup
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          CLEAN_ALL: true
          BBL_STATE_DIR: cf-with-consul
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
      - task: destroy-infrastructure
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        image: cf-deployment-concourse-tasks-docker-image
        input_mapping:
          bbl-state: updated-bbl-state
        params:
          BBL_STATE_DIR: cf-with-consul
          BBL_GCP_SERVICE_ACCOUNT_KEY: ((cf_infra_gcp_service_account_key))
        on_failure:
          put: infrastructure-ci-bbl-states
          params:
            rebase: true
            repository: updated-bbl-state

- name: create-final-release
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo
      resource: consul-release-develop
      passed: [deploy-cf]
    - get: release-repo-master
      resource: consul-release-master
    - get: oss-s3-buckets-stack
  - task: create-final-release
    file: ci/scripts/common/create-final-release/task.yml
    params:
      RELEASE_NAME: consul
  - put: consul-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v
  - put: consul-release-gh
    params:
      name: final-release-repo/release_name
      tag: final-release-repo/version_number
      tag_prefix: v
      globs:
      - final-release-repo/consul-release-*.tgz

- name: merge-master-into-develop
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo-master
      resource: consul-release-master
      trigger: true
    - get: release-repo
      resource: consul-release-merge-target
  - task: merge-master-into-develop
    file: ci/scripts/common/merge-master-into-develop/task.yml
  - put: consul-release-merge-target
    params:
      repository: final-release-repo
