---
groups:
- name: consul
  jobs:
  - check-git-submodules
  - deploy-sample-manifest
  - merge-master-into-develop
  - releasable
  - create-final-release

resources:
- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

- name: bosh-deployment
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: consul-release-develop
  type: git
  source:
    branch: develop
    ignore_paths: [.final_builds, releases]
    uri: https://github.com/cloudfoundry-incubator/consul-release.git

- name: consul-release-master
  type: git
  source:
    branch: master
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: consul-release-gh
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: consul-release
    access_token: {{cf_infra_bot_user_github_access_token}}

- name: consul-release-merge-target
  type: git
  source:
    branch: develop
    private_key: {{consul-release-private-key}}
    uri: git@github.com:cloudfoundry-incubator/consul-release.git

- name: oss-s3-buckets-stack
  type: git
  source:
    branch: master
    private_key: {{oss-s3-buckets-stack-private-key}}
    uri: git@github.com:cloudfoundry/oss-s3-buckets-stack.git

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

jobs:
- name: check-git-submodules
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: repo
      resource: consul-release-develop
      trigger: true
  - task: check-git-submodules
    file: ci/scripts/common/check-git-submodules/task.yml

- name: deploy-sample-manifest
  plan:
  - aggregate:
    - get: release
      resource: consul-release-develop
      passed:
      - check-git-submodules
      trigger: true
    - get: ci
      resource: infrastructure-ci
    - get: bosh-deployment
    - get: gcp-stemcell
  - task: deploy-sample-manifest
    file: ci/scripts/common/deploy-sample-manifests/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      BBL_GCP_PROJECT_ID: {{gcp_project_id}}
      BBL_GCP_REGION: {{gcp_region}}
      BBL_GCP_ZONE: {{gcp_zone}}
      CLOUD_CONFIG: manifests/cloud_config.yml
      MANIFESTS: manifests/multi-az-with-ssl.yml

- name: releasable
  serial: true
  plan:
  - aggregate:
    - get: consul-release-develop
      passed:
      - deploy-sample-manifest
      trigger: true

- name: create-final-release
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo
      resource: consul-release-develop
      passed: [releasable]
      trigger: true
    - get: release-repo-master
      resource: consul-release-master
    - get: oss-s3-buckets-stack
  - task: create-final-release
    file: ci/scripts/common/create-final-release/task.yml
    params:
      RELEASE_NAME: consul
  - put: consul-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v
  - put: consul-release-gh
    params:
      name: final-release-repo/release_name
      tag: final-release-repo/version_number
      tag_prefix: v
      globs:
      - final-release-repo/consul-release-*.tgz

- name: merge-master-into-develop
  serial: true
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: release-repo-master
      resource: consul-release-master
      trigger: true
    - get: release-repo
      resource: consul-release-merge-target
  - task: merge-master-into-develop
    file: ci/scripts/common/merge-master-into-develop/task.yml
  - put: consul-release-merge-target
    params:
      repository: final-release-repo
