resources:
- name: mkdocs-pivotal-theme
  type: git
  source:
    uri: https://github.com/pivotal/mkdocs-pivotal-theme
- name: docs-v1.0.0
  type: git
  source:
    uri: git@github.com:pivotal/control-plane-docs
    branch: v1.0.0
    private_key: ((docs-github-deploy-key.private_key))
- name: docs-v0.0.37
  type: git
  source:
    uri: git@github.com:pivotal/control-plane-docs
    branch: v0.0.37
    private_key: ((docs-github-deploy-key.private_key))
- name: docs-develop
  type: git
  source:
    uri: git@github.com:pivotal/control-plane-docs
    branch: develop
    private_key: ((docs-github-deploy-key.private_key))
- name: docs-app
  type: cf
  source:
    api: api.run.pivotal.io
    client_id: ((pcf_infra_prod_service_account.username))
    client_secret: ((pcf_infra_prod_service_account.password))
    organization: ((pws_organization))
    space: ((pws_space))

jobs:
- name: build-docs
  serial: true
  plan:
    - get: mkdocs-pivotal-theme
    - get: docs-v1.0.0
      trigger: true
    - get: docs-v0.0.37
      trigger: true
    - get: docs-develop
      trigger: true
    - task: build-docs
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: { repository: internalpcfplatformautomation/docs }
        inputs:
        - name: docs-v1.0.0
        - name: docs-v0.0.37
        - name: docs-develop
        - name: mkdocs-pivotal-theme
        outputs:
        - name: cf-app
        run:
          path: mkdocs-pivotal-theme/ci/build-docs/build_docs.rb
          args: [
            '--output-dir', './cf-app',
            '--docs-dir', '.',
            '--docs-prefix', 'docs',
            '--site-prefix', 'control-plane',
            '--domains', 'docs.pivotal.io'
            ]
    - put: docs-app
      params:
        manifest: cf-app/manifest.yml
        path: cf-app
        current_app_name: control-plane-docs
        show_app_log: true
