---
groups:
- name: dockerfiles
  jobs:
  - minimal-docker-image
  - golang-docker-image
  - deployment-docker-image
  - mkdocs-docker-image
  - terraform-image
  - cf-deployment-concourse-tasks-w-gcloud-image

resources:
- name: terraform-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master
    paths:
    - dockerfiles/terraform

- name: deployment-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master
    paths:
    - dockerfiles/deployment

- name: golang-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master
    paths:
    - dockerfiles/golang

- name: minimal-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master
    paths:
    - dockerfiles/minimal

- name: mkdocs-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master
    paths:
    - dockerfiles/mkdocs

- name: cf-deployment-concourse-tasks-w-gcloud-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master
    paths:
    - dockerfiles/cf-deployment-concourse-tasks-w-gcloud

- name: ubuntu-docker-image
  type: docker-image
  source:
    repository: ubuntu
    tag: "14.04"

- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.15.0

- name: cf-deployment-concourse-tasks-w-gcloud-image
  type: docker-image
  source:
    repository: cfinfrastructure/cf-deployment-concourse-tasks-w-gcloud
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: minimal-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/minimal
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: golang-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/golang
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: deployment-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/deployment
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: terraform-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/terraform
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: mkdocs-docker-image
  type: docker-image
  source:
    repository: cfinfrastructure/mkdocs
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: bbl-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-bootloader
    access_token: {{cf_infra_bot_user_github_access_token}}

jobs:
- name: minimal-docker-image
  public: true
  plan:
  - do:
    - aggregate:
      - get: ubuntu-docker-image
        trigger: true
        params:
          skip_download: true
      - get: infrastructure-ci
        resource: minimal-dockerfile
        trigger: true
    - put: minimal-docker-image
      params:
        build: infrastructure-ci/dockerfiles/minimal
        cache: false

- name: mkdocs-docker-image
  public: true
  plan:
  - do:
    - aggregate:
      - get: ubuntu-docker-image
        trigger: true
        params:
          skip_download: true
      - get: infrastructure-ci
        resource: mkdocs-dockerfile
        trigger: true
    - put: mkdocs-docker-image
      params:
        build: infrastructure-ci/dockerfiles/mkdocs
        cache: false

- name: golang-docker-image
  public: true
  plan:
  - do:
    - aggregate:
      - get: minimal-docker-image
        passed: [minimal-docker-image]
        trigger: true
        params:
          skip_download: true
      - get: infrastructure-ci
        resource: golang-dockerfile
        trigger: true
    - put: golang-docker-image
      params:
        build: infrastructure-ci/dockerfiles/golang
        cache: false

- name: deployment-docker-image
  public: false
  plan:
  - do:
    - aggregate:
      - get: golang-docker-image
        passed: [golang-docker-image]
        trigger: true
        params:
          skip_download: true
      - get: infrastructure-ci
        resource: deployment-dockerfile
        trigger: true
      - get: bbl-release
        trigger: true
    - put: deployment-docker-image
      params:
        build: infrastructure-ci/dockerfiles/deployment
        build_args:
          GITHUB_TOKEN: {{cf_infra_bot_user_github_access_token}}
        cache: false

- name: terraform-image
  public: true
  plan:
  - do:
    - aggregate:
      - get: deployment-docker-image
        passed: [deployment-docker-image]
        trigger: true
        params:
          skip_download: true
      - get: infrastructure-ci
        resource: terraform-dockerfile
        trigger: true
    - put: terraform-docker-image
      params:
        build: infrastructure-ci/dockerfiles/terraform
        cache: false

- name: cf-deployment-concourse-tasks-w-gcloud-image
  public: true
  plan:
  - do:
    - aggregate:
      - get: cf-deployment-concourse-tasks-image
        trigger: true
      - get: infrastructure-ci
        resource: cf-deployment-concourse-tasks-w-gcloud-dockerfile
        trigger: true
    - put: cf-deployment-concourse-tasks-w-gcloud-image
      params:
        build: infrastructure-ci/dockerfiles/cf-deployment-concourse-tasks-w-gcloud
        cache: false
