---
groups:
- name: infrastructure-ci
  jobs:
  - unit-tests
- name: windows-ci-worker
  jobs:
  - setup-worker-infrastructure
  - deploy-worker
  - delete-worker-deployment
  - teardown-worker-infrastructure

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    branch: master

- name: infrastructure-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/infrastructure-ci
    branch: master

- name: infrastructure-ci-bbl-states
  type: git
  source:
    uri: git@github.com:cloudfoundry/infrastructure-ci-bbl-states.git
    private_key: ((cf_infra_bot_user_github_private_key.private_key))
    branch: master
    paths:
    - ci-workers

- name: concourse-windows-master
  type: git
  source:
    uri: https://github.com/pivotal-cf-experimental/concourse-windows-release.git
    branch: master

- name: windows-stemcell
  type: s3
  source:
    bucket: bosh-windows-stemcells
    regexp: light-bosh-stemcell-(.*)-google-kvm-windows2012R2-go_agent.tgz

jobs:
- name: unit-tests
  public: true
  plan:
  - do:
    - get: ci
      resource: infrastructure-ci
      trigger: true
    - task: infrastructure-ci-tests
      file: ci/scripts/infrastructure-ci/run-tests/task.yml
      params:
        AWS_ACCESS_KEY_ID: ((aws_access_key_id))
        AWS_SECRET_ACCESS_KEY: ((aws_secret_access_key))
        GOVCLOUD_AWS_SECRET_ACCESS_KEY: ((govcloud_images_secret_access_key))
        GOVCLOUD_AWS_ACCESS_KEY_ID: ((govcloud_images_access_key_id))

# Infrastructure
- name: setup-worker-infrastructure
  public: true
  serial: true
  serial_groups: [infrastructure]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
  - task: bbl-up
    file: ci/scripts/common/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: ((gcp_service_account_key))
      BBL_GCP_REGION: ((gcp_region))
      BBL_GCP_ZONE: ((gcp_zone))
      BBL_STATE_DIR: windows-ci-worker
      BBL_NAME: windows-ci-worker
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-worker
  public: true
  serial: true
  serial_groups: [infrastructure]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
      passed: [setup-worker-infrastructure]
      trigger: true
    - get: windows-stemcell
      resource: windows-stemcell
    - get: concourse-windows
      resource: concourse-windows-master
  - task: deploy-windows-worker
    file: ci/scripts/infrastructure-ci/deploy-concourse-windows-worker/task.yml
    params:
      DEPLOYMENT_NAME: wings-windows-worker
      BBL_STATE_DIR: windows-ci-worker
      CONCOURSE_TEAM: ((wings_concourse_team))
      TSA_HOST: ((wings_tsa_host))
      TSA_PUBLIC_KEY: ((wings_tsa_public_key))
      TSA_WORKER_PRIVATE_KEY: ((windows_tsa_worker_private_key.private_key))

- name: delete-worker-deployment
  public: true
  serial: true
  serial_groups: [infrastructure]
  plan:
  - aggregate:
    - get: bbl-state
      resource: infrastructure-ci-bbl-states
    - get: ci
      resource: infrastructure-ci
    - get: cf-deployment-concourse-tasks
  - task: delete-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    params:
      DEPLOYMENT_NAME: wings-windows-worker
      BBL_STATE_DIR: windows-ci-worker
  - task: cleanup-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: ci-workers
      CLEAN_ALL: true

- name: teardown-worker-infrastructure
  public: true
  serial: true
  serial_groups: [infrastructure]
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: bbl-states-repo
      resource: infrastructure-ci-bbl-states
  - task: bbl-destroy
    file: ci/scripts/common/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: windows-ci-worker
    ensure:
      put: infrastructure-ci-bbl-states
      params:
        repository: bbl-states-repo-out
        rebase: true
