groups:
- name: leftovers
  jobs:
  - test

resources:
- name: leftovers
  type: git
  source:
    branch: master
    uri: https://github.com/genevieve/leftovers.git

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

jobs:
- name: test
  plan:
  - aggregate:
    - get: ci
      resource: infrastructure-ci
    - get: leftovers
      trigger: true
  - task: test
    file: ci/scripts/leftovers/test/task.yml
