groups:
- name: terraforming
  jobs:
  - terraforming-aws
  - terraforming-azure
  - terraforming-gcp

resources:
- name: terraforming-aws
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/terraforming-aws.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: terraforming-azure
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/terraforming-azure.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: terraforming-gcp
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/terraforming-gcp.git
    private_key: {{cf_infra_bot_user_github_private_key}}

- name: infrastructure-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/infrastructure-ci.git

jobs:
- name: terraforming-aws
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming-aws
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: apply-and-destroy
    file: ci/scripts/terraforming/aws/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_SSL_CERT: {{ssl_cert}}
      AWS_SSL_PRIVATE_KEY: {{ssl_private_key}}

- name: terraforming-azure
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming-azure
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: apply-and-destroy
    file: ci/scripts/terraforming/azure/task.yml
    params:
      AZURE_SUBSCRIPTION_ID: {{azure_subscription_id}}
      AZURE_TENANT_ID: {{azure_tenant_id}}
      AZURE_CLIENT_ID: {{azure_client_id}}
      AZURE_CLIENT_SECRET: {{azure_client_secret}}
      AZURE_VM_ADMIN_PASSWORD: {{azure_vm_admin_password}}

- name: terraforming-gcp
  serial: true
  public: false
  plan:
  - aggregate:
    - get: terraforming-gcp
      trigger: true
    - get: ci
      resource: infrastructure-ci
  - task: apply-and-destroy
    file: ci/scripts/terraforming/gcp/task.yml
    params:
      GCP_PROJECT_ID: {{gcp_project_id}}
      GCP_SERVICE_ACCOUNT_KEY: {{gcp_service_account_key}}
      GCP_SSL_CERT: {{ssl_cert}}
      GCP_SSL_PRIVATE_KEY: {{ssl_private_key}}
