---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final


resources:
- name: vsphere-pautomator-ci
  type: git
  source:
    branch: vsphere-wip
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: pautomator
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
jobs:
- name: create-opsman
  build_logs_to_retain: 101
  plan:
  - aggregate:
    - get: ci
      resource: vsphere-pautomator-ci
      trigger: true
    - get: pautomator
  - task: create-opsman
    file: ci/scripts/vsphere-pautomator/create-opsman/task.yml
    params:
      OPS_DISKTYPE: thin
      OPS_PRIVATE_IP: ((vcenter-pautomator-opsman-private-ip))
      OPS_DNS: ((vcenter-pautomator-opsman-dns))
      OPS_NTP: time.svc.pivotal.io
      OPS_SSH_PASSWORD: ((vcenter-pautomator-opsman-ssh-password))
      OPS_HOSTNAME: ((vcenter-pautomator-opsman-url))
      OPS_NETWORK: ((vcenter-pautomator-opsman-network))
      OPS_NETMASK: 255.255.255.0
      OPS_GATEWAY: 192.168.1.1
      OPS_VM_NAME: pivotal-ops-mamager-2
      OPS_MEMORY: 10
      OPS_CPU: 10
      OPS_VCENTER_URL: ((vcenter-pautomator-url))
      OPS_VCENTER_USERNAME: ((vcenter-pautomator-username))
      OPS_VCENTER_PASSWORD: ((vcenter-pautomator-password))
      OPS_VCENTER_DATASTORE: ((vcenter-pautomator-datastore))
      OPS_VCENTER_DATACENTER: ((vcenter-pautomator-datacenter))
      OPS_VCENTER_INSECURE: 1
      OPS_VCENTER_RESOURCE_POOL: ((vcenter-pautomator-resource-pool))
      OPS_VCENTER_CA_CERT: ((vcenter-pautomator-ca-cert))
