---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: vsphere-p-automator-ci
  type: git
  source:
    branch: vsphere-wip
    uri: https://github.com/cloudfoundry/infrastructure-ci.git
- name: platform-automation-release
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
- name: ops-manager-release
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager

jobs:
- name: create-opsman
  plan:
  - aggregate:
    - get: ci
      resource: vsphere-p-automator-ci
      trigger: true
    - get: platform-automation-image
      resource: platform-automation-release
      trigger: true
      params:
        globs: ["*image*"]
        unpack: true
    - get: ops-manager-image
      resource: ops-manager-release
      trigger: true
      params:
        globs: ["*vsphere*"]
  - task: create-opsman
    image: platform-automation-image
    file: ci/scripts/vsphere-p-automator/create-opsman/task.yml
    tags: [pez-403]
    params:
      OPS_DISKTYPE: thin
      OPS_PRIVATE_IP: ((vcenter-p-automator-opsman-private-ip))
      OPS_DNS: ((vcenter-p-automator-opsman-dns))
      OPS_NTP: time.svc.pivotal.io
      OPS_SSH_PASSWORD: ((vcenter-p-automator-opsman-ssh-password))
      OPS_HOSTNAME: ((vcenter-p-automator-opsman-url))
      OPS_NETWORK: ((vcenter-p-automator-opsman-network))
      OPS_NETMASK: 255.255.255.0
      OPS_GATEWAY: 192.168.3.1
      OPS_VM_NAME: pivotal-ops-manager
      OPS_MEMORY: 10
      OPS_CPU: 10
      OPS_VCENTER_URL: ((vcenter-p-automator-url))
      OPS_VCENTER_USERNAME: ((vcenter-p-automator-username))
      OPS_VCENTER_PASSWORD: ((vcenter-p-automator-password))
      OPS_VCENTER_DATASTORE: ((vcenter-p-automator-datastore))
      OPS_VCENTER_DATACENTER: ((vcenter-p-automator-datacenter))
      OPS_VCENTER_INSECURE: 1
      OPS_VCENTER_RESOURCE_POOL: ((vcenter-p-automator-resource-pool))
      OPS_VCENTER_CA_CERT: ((vcenter-p-automator-ca-cert))
