#!/usr/bin/env bash

set -e -x -u

ROOT="${PWD}"
VERSION=$(cat "${root}/az-automation-release/version")

shaOS=$(shasum -a 256 az-automation-release/az-automation-*_osx | cut -d ' ' -f 1)
shaLinux=$(shasum -a 256 az-automation-release/az-automation-*_linux_x86-64 | cut -d ' ' -f 1)

pushd homebrew-tap
  cat <<EOF > az-automation.rb
class AzAutomation < Formula
  desc "Command line utility for cleaning up orphaned IAAS resources."
  homepage "https://github.com/genevievelesperance/az-automation"
  version "v${version}"

  if OS.mac?
    url "https://github.com/genevievelesperance/az-automation/releases/download/#{version}/az-automation-#{version}_osx"
    sha256 "${shaOS}"
  elsif OS.linux?
    url "https://github.com/genevievelesperance/az-automation/releases/download/#{version}/az-automation-#{version}_linux_x86-64"
    sha256 "${shaLinux}"
  end

  depends_on :arch => :x86_64
  depends_on "az" => "2.0.25"

  def install
    binary_name = "az-automation"
    if OS.mac?
      bin.install "az-automation-#{version}_osx" => binary_name
    elsif OS.linux?
      bin.install "az-automation-#{version}_linux_x86-64" => binary_name
    end
  end

  test do
    system "#{bin}/#{binary_name} --help"
  end
end
EOF

  cat az-automation.rb

  git add az-automation.rb
  if ! [ -z "$(git status --porcelain)" ];
  then
    git config --global user.email "cf-infrastructure@pivotal.io"
    git config --global user.name "CF Infrastructure"
    git commit -m "Release az-automation ${version}"
  else
    echo "No new version to commit"
  fi
popd

cp -R homebrew-tap updated-homebrew-tap
