#!/bin/bash -exu

ROOT="${PWD}"

mv bosh-cli/bosh-cli-*-linux-amd64 /usr/local/bin/bosh
chmod +x /usr/local/bin/bosh

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

set +x
  echo "${GCP_SERVICE_ACCOUNT_KEY}" > service_account.key.json
  service_account_key_path="${PWD}/service_account.key.json"
set -x

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  export GCP_SERVICE_ACCOUNT_KEY="${service_account_key_path}"
  ./bosh-bootloader/scripts/acceptance_tests gcp
popd > /dev/null
