#!/bin/bash -exu

ROOT="${PWD}"

function main() {
  local cfdir
  cfdir="${GOPATH}/src/github.com/cloudfoundry"

  mkdir -p "${cfdir}"

  ln -s "${ROOT}/bosh-bootloader" "${cfdir}/bosh-bootloader"

  pushd "${cfdir}/bosh-bootloader" > /dev/null
    go get -u github.com/golang/dep/cmd/dep

    dep ensure -update github.com/genevieve/leftovers

    status="$(git status --short)"

    if [[ ${status} != "" ]]
    then
      git add .

      git config user.email "cf-infrastructure@pivotal.io"
      git config user.name "cf-infra-bot"

      git commit -m 'bump leftovers'
    else
      echo "No changes to commit"
    fi

    cp -r . ${ROOT}/bosh-bootloader-updated
  popd > /dev/null
}

main
