#!/bin/bash -exu

ROOT="${PWD}"

function main() {
  local cfdir
  cfdir="${GOPATH}/src/github.com/cloudfoundry"

  mkdir -p "${cfdir}"

  ln -s "${ROOT}/bosh-bootloader" "${cfdir}/bosh-bootloader"

  pushd "${cfdir}/bosh-bootloader" > /dev/null
    go get -u github.com/golang/dep/cmd/dep

    dep ensure -update github.com/genevieve/leftovers

    git commit -am 'bump leftovers'

    cp -r . ${ROOT}/bosh-bootloader-updated
  popd > /dev/null
}

main
