#!/bin/bash -exu

pushd terraforming-gcp > /dev/null

  terraform init

  trap 'terraform destroy -force; exit' EXIT

  echo 'env_name = "terraforming-gcp-env"' > terraform.tfvars
  echo "project = \"${GCP_PROJECT_ID}\"" >> terraform.tfvars
  echo 'region = "us-central1"' >> terraform.tfvars
  echo 'zones = ["us-central1-a", "us-central1-b", "us-central1-c"]' >> terraform.tfvars
  echo 'opsman_image_url = "https://storage.googleapis.com/ops-manager-us/pcf-gcp-2.0-build.264.tar.gz"' >> terraform.tfvars
  echo 'dns_suffix = "terraforming-gcp-env.cf-app.com"' >> terraform.tfvars
  echo 'isolation_segment = true' >> terraform.tfvars
  echo 'external_database = 1' >> terraform.tfvars

  set +x
    echo "service_account_key = <<SERVICE_ACCOUNT_KEY" >> terraform.tfvars
    echo "${GCP_SERVICE_ACCOUNT_KEY}" >> terraform.tfvars
    echo "SERVICE_ACCOUNT_KEY" >> terraform.tfvars

    cert="$(echo "${GCP_SSL_CERT}" | awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}')"
    echo -e "ssl_cert = <<SSL_CERT\n${cert}SSL_CERT" >> terraform.tfvars

    key="$(echo "${GCP_SSL_PRIVATE_KEY}" | awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}')"
    echo -e "ssl_private_key = <<SSL_KEY\n${key}SSL_KEY" >> terraform.tfvars

    echo -e "iso_seg_ssl_cert = <<SSL_CERT\n${cert}SSL_CERT" >> terraform.tfvars
    echo -e "iso_seg_ssl_private_key = <<SSL_KEY\n${key}SSL_KEY" >> terraform.tfvars
  set -x

  terraform validate

  terraform plan -out=plan

  TF_LOG=TRACE TF_LOG_PATH=tf-logs.txt terraform apply plan

  terraform destroy -force

popd > /dev/null
texplate execute "${configure_om_dir}/config-director-template.yml" -f "${cwd}/tfoutput.json" -o yaml > "${cwd}/director-config.yml"
