#!/bin/bash -xu

pushd terraforming-gcp > /dev/null

  terraform init

  echo 'env_name = "terraforming-gcp-env"' > terraform.tfvars
  echo "project = \"${GCP_PROJECT_ID}\"" >> terraform.tfvars
  echo 'region = "us-central1"' >> terraform.tfvars
  echo 'zones = ["us-central1-a", "us-central1-b", "us-central1-c"]' >> terraform.tfvars
  echo 'opsman_image_url = "https://storage.googleapis.com/ops-manager-us/pcf-gcp-1.12.0.tar.gz"' >> terraform.tfvars
  echo 'dns_suffix = "terraforming-gcp-env.cf-app.com"' >> terraform.tfvars
  echo 'external_database = "true"' >> terraform.tfvars

  set +x
    echo "service_account_key = <<SERVICE_ACCOUNT_KEY" >> terraform.tfvars
    echo "${GCP_SERVICE_ACCOUNT_KEY}" >> terraform.tfvars
    echo "SERVICE_ACCOUNT_KEY" >> terraform.tfvars

    cert="$(echo "${GCP_SSL_CERT}" | awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}')"
    echo -e "ssl_cert = <<SSL_CERT\n${cert}SSL_CERT" >> terraform.tfvars

    key="$(echo "${GCP_SSL_PRIVATE_KEY}" | awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}')"
    echo -e "ssl_private_key = <<SSL_KEY\n${key}SSL_KEY" >> terraform.tfvars
  set -x

  set -e
    terraform plan -out=plan
  set +e

  terraform apply plan

  terraform destroy -force

popd > /dev/null
