#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry-incubator"

  pushd "${GOPATH}/src/github.com/cloudfoundry-incubator" > /dev/null
    ln -s "${root_dir}/consul-release"
    chpst -u testuser:testuser ./consul-release/src/confab/scripts/test
  popd > /dev/null
}

main "${PWD}"
