#!/bin/bash -exu

main() {
  commit_sha=$(git -C terraforming rev-parse HEAD)
  version="v$(cat version/version)"
  echo -n "${version}" > release/version
  echo -n "${commit_sha}" > release/commitish

  rm -rf terraforming/ci terraforming/scripts terraforming/.envrc

  if [ -z ${RELEASE_NAME} ]; then
    RELEASE_NAME="terraforming-${IAAS}"
  fi

  tar cvzf "release/${RELEASE_NAME}-${version}.tar.gz" terraforming
}

main "$@"
