#!/bin/bash

main() {
  commit_sha=$(git -C terraforming rev-parse HEAD)
  version="v$(cat version/version)"
  echo -n "${version}" > release/version
  echo -n "${commit_sha}" > release/commitish

  rm -rf terraforming/ci terraforming/scripts terraforming/.envrc
  tar cvzf "release/terraforming-${IAAS}-${version}.tar.gz" terraforming
}

main "$@"
