#!/bin/bash -exu

function main() {
  local root_dir
  root_dir="${1}"

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"
  pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
    ln -s "${root_dir}/ci" infrastructure-ci
    pushd infrastructure-ci > /dev/null
      ginkgo \
        -p \
        -r \
        -skipPackage apps/bbl-latest \
        -race \
        -randomizeAllSpecs \
        -randomizeSuites \
        .
    popd > /dev/null
  popd > /dev/null
}

main "${PWD}"
