#!/bin/bash -exu

ROOT="${PWD}"
BBL_VERSION=$(cat "${ROOT}/bbl-version/number")

function main() {
  local bosh_bootloader_commit_sha
  local bosh_deployment_commit_sha

  mkdir -p "${GOPATH}/src/github.com/cloudfoundry/"
  ln -s "${ROOT}/bosh-bootloader" "${GOPATH}/src/github.com/cloudfoundry/"
  bosh_bootloader_commit_sha=$(git -C "${ROOT}/bosh-bootloader" rev-parse HEAD)
  bosh_deployment_commit_sha=$(git -C "${ROOT}/bosh-bootloader/vendor/github.com/cloudfoundry/bosh-deployment" rev-parse HEAD)

  pushd "${GOPATH}/src/github.com/cloudfoundry/bosh-bootloader/bbl" > /dev/null
    build_bbl
  popd > /dev/null

  pushd "${ROOT}/builds" > /dev/null
    echo -n "v${BBL_VERSION}" > name
    echo -n "${bosh_bootloader_commit_sha}" > commitish
    echo -n "- *Current bosh-deployment: cloudfoundry/bosh-deployment@${bosh_deployment_commit_sha}*" > body
  popd > /dev/null
}

function build_bbl() {
  echo "Building 64-bit Linux"
  CGO_ENABLED=0 GOARCH=amd64 GOOS=linux \
    go build -a -tags netgo -installsuffix netgo \
    -ldflags "-X main.Version=${BBL_VERSION}" \
    -o "${ROOT}/builds/bin/bbl-v${BBL_VERSION}_linux_x86-64" .

  echo "Building 64-bit Darwin"
  GOARCH=amd64 GOOS=darwin \
    go build \
    -ldflags "-X main.Version=${BBL_VERSION}" \
    -o "${ROOT}/builds/bin/bbl-v${BBL_VERSION}_osx" .
}

main
