#!/bin/bash -exu

ROOT="${PWD}"

trap moveLogFiles EXIT
moveLogFiles()
{
  if [[ -e "${BOSH_LOG_PATH}" ]]; then
    cp ${BOSH_LOG_PATH} "${ROOT}/bosh-logs/bosh-logs.log"
  else
    echo "Failed before bosh cli" > "${ROOT}/bosh-logs/bosh-logs.log"
  fi
  exit 1
}

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  export TF_LOG=DEBUG
  export TF_LOG_PATH="${ROOT}/tf-logs.txt"
  export BOSH_LOG_LEVEL=debug
  export BOSH_LOG_PATH="${ROOT}/bosh-logs.txt"
  ./bosh-bootloader/scripts/acceptance_tests ${BBL_TEST_PACKAGES}
popd > /dev/null
