#!/bin/bash -exu

ROOT="${PWD}"

mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

pushd "${GOPATH}/src/github.com/cloudfoundry" > /dev/null
  ln -s "${ROOT}/bosh-bootloader"

  ./bosh-bootloader/scripts/acceptance_tests ${BBL_TEST_PACKAGES}
popd > /dev/null
