#!/bin/bash -exu

export ROOT="${PWD}"

function main() {
  setup_bosh_env_vars

  local raw_deployments
  set +x
  raw_deployments=$(curl -sk https://${BOSH_CLIENT}:${BOSH_CLIENT_SECRET}@${BOSH_ENVIRONMENT}:25555/deployments)
  set -x

  local deployments
  deployments=$(echo "${raw_deployments}" | jq 'map(select(.name | contains('\"${DEPLOYMENTS_WITH_WORD}\"')))' | jq .[].name)

  if [ -n "${deployments}" ]
  then
    echo "${deployments}" | xargs -n 1 -P 5 -I{} bosh -n -d {} delete-deployment --force
  fi

  echo "cleaning up orphaned disks and releases"
  bosh -n clean-up
}

function setup_bosh_env_vars() {
  set +x
  pushd "${ROOT}/bbl-states-repo/${BBL_STATE_DIR}" > /dev/null
    export BOSH_ENVIRONMENT=$(bbl director-address)
    export BOSH_CA_CERT="$(bbl director-ca-cert)"
    export BOSH_CLIENT=$(bbl director-username)
    export BOSH_CLIENT_SECRET=$(bbl director-password)
  popd > /dev/null
  set -x
}

main
