#!/bin/bash -exu

export ROOT="${PWD}"

function main() {
  setup_bosh_env_vars

  for i in $(bosh deployments | grep "${DEPLOYMENTS_WITH_WORD}" | awk '{ print $1 }' | uniq); do
    bosh -d $i -n delete-deployment
  done

  echo "cleaning up orphaned disks and releases"
  bosh -n clean-up
}

function setup_bosh_env_vars() {
  if [ -r "${ROOT}/bbl-states-repo/${BBL_STATE_DIR}/bbl-state.json" ]; then
    set +x
    pushd "${ROOT}/bbl-states-repo/${BBL_STATE_DIR}" > /dev/null
      export BOSH_ENVIRONMENT=$(bbl director-address)
      export BOSH_CA_CERT="$(bbl director-ca-cert)"
      export BOSH_CLIENT=$(bbl director-username)
      export BOSH_CLIENT_SECRET=$(bbl director-password)
    popd > /dev/null
    set -x
  fi
}

main
