#!/bin/bash -exu

function main() {
  local raw_deployments
  set +x
  raw_deployments=$(curl -sk https://${BOSH_CLIENT}:${BOSH_CLIENT_SECRET}@${BOSH_ENVIRONMENT}:25555/deployments)
  set -x

  local deployments
  deployments=$(echo "${raw_deployments}" | jq 'map(select(.name | contains('\"${DEPLOYMENTS_WITH_WORD}\"')))' | jq .[].name)

  if [ -n "${deployments}" ]
  then
    echo "${deployments}" | xargs -n 1 -P 5  bosh -n delete-deployment --force
  fi

  echo "cleaning up orphaned disks and releases"
  bosh -n clean-up
}

main
