#!/bin/bash -exu

export BBL_NAME=""

function check_fast_fails() {
  set +x
  if [ -z "${BBL_STATE_DIR}" ]; then
    echo "\$BBL_STATE_DIR is a required parameter for gcp.  Please set the BBL_STATE_DIR."
    exit 1
  fi
  set -x
}

function commit_bbl_state_file() {
  local root_dir
  root_dir="${1}"

  pushd "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}" > /dev/null
    if [[ -n $(git status --porcelain) ]]; then
      git config user.name "CI Infra Bot"
      git config user.email "cf-infrastructure@pivotal.io"
      git add --all bbl-state.json
      git commit -m "Update/remove ${BBL_NAME} bbl-state.json"
    fi
  popd > /dev/null

  pushd "${root_dir}" > /dev/null
    shopt -s dotglob
    cp -R bbl-states-repo/* bbl-states-repo-out/
  popd > /dev/null
}

function main() {
  local root_dir
  root_dir="${1}"

  check_fast_fails

  BBL_NAME="$(bbl --state-dir "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}" env-id)"

  mkdir -p "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}"
  bbl --debug --state-dir "${root_dir}/bbl-states-repo/${BBL_STATE_DIR}" destroy --no-confirm --skip-if-missing > bbl_destroy.log
}

trap "commit_bbl_state_file ${PWD}" EXIT

main ${PWD}
