#!/bin/bash -exu

function deploy_diego() {
  local root_dir
  root_dir="${1}"

  /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" download manifest consul-cf-deployment cf.yml

  pushd diego-release > /dev/null
    ./scripts/generate-deployment-manifest \
      -c "${root_dir}/cf.yml" \
      -i "${root_dir}/consul-cf-env/stubs/diego/iaas-settings.yml" \
      -p "${root_dir}/consul-cf-env/stubs/diego/property-overrides.yml" \
      -s "${root_dir}/consul-cf-env/stubs/diego/diego-sql.yml" \
      -n "${root_dir}/consul-cf-env/stubs/diego/instance-count-overrides.yml" \
      -v "${root_dir}/consul-cf-env/stubs/diego/release-versions.yml" \
      -g \
      > "${root_dir}/diego.yml"
  popd > /dev/null

  /opt/rubies/ruby-2.2.4/bin/bosh -n \
    -d diego.yml \
    -t "${BOSH_DIRECTOR}" \
    deploy
}

function upload_release() {
  local release
  release="${1}"

  /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" upload release "https://bosh.io/d/github.com/${release}"
}

function upload_stemcell() {
  local root_dir
  root_dir="${1}"

  pushd "${root_dir}/stemcell" > /dev/null
    /opt/rubies/ruby-2.2.4/bin/bosh -t "${BOSH_DIRECTOR}" upload stemcell stemcell.tgz --skip-if-exists
  popd > /dev/null
}

function main() {
  local root_dir
  root_dir="${1}"

  upload_stemcell "${root_dir}"

  upload_release "cloudfoundry/cflinuxfs2-rootfs-release"
  upload_release "cloudfoundry/diego-release"
  upload_release "cloudfoundry/garden-runc-release"
  upload_release "cloudfoundry-incubator/etcd-release"

  deploy_diego "${root_dir}"
}

main "${PWD}"
