#!/bin/bash -exu

ROOT="${PWD}"
function main() {
  cp -a "${ROOT}/bbl-docs-repo/.git" "${ROOT}/bbl-docs/.git"
  pushd "${ROOT}/bbl-release-official"
    mkdir src
    tar -xf source.tar.gz -C src --strip-components=1
    pushd src
      mkdocs build
      cp -a site/. "${ROOT}/bbl-docs"
    popd > /dev/null
  popd > /dev/null
}

main
