#!/bin/bash -exu

ROOT="${PWD}"
JUMPBOX_DEPLOYMENT_VENDOR_PATH="${ROOT}/bosh-bootloader/vendor/github.com/cppforlife"
BOSH_DEPLOYMENT_VENDOR_PATH="${ROOT}/bosh-bootloader/vendor/github.com/cloudfoundry"

function main() {
  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

  mkdir -p "${JUMPBOX_DEPLOYMENT_VENDOR_PATH}"
  mkdir -p "${BOSH_DEPLOYMENT_VENDOR_PATH}"

  pushd ${JUMPBOX_DEPLOYMENT_VENDOR_PATH}
    local commitish
    commitish=$(git rev-parse HEAD)

    cp -R ${ROOT}/jumpbox-deployment/ .
    echo "- *Current jumpbox-deployment: cloudfoundry/jumpbox-deployment/@${commitish}*" > ${ROOT}/bosh-bootloader/deployment-versions.txt
    rm -rf jumpbox-deployment/.git
  popd

  pushd ${BOSH_DEPLOYMENT_VENDOR_PATH}
    local commitish
    commitish=$(git rev-parse HEAD)

    cp -R ${ROOT}/bosh-deployment/ .
    echo "- *Current bosh-deployment: cloudfoundry/bosh-deployment/@${commitish}*" >> ${ROOT}/bosh-bootloader/deployment-versions.txt
    rm -rf bosh-deployment/.git
  popd

  pushd "${ROOT}/bosh-bootloader" > /dev/null
    go get -u github.com/jteeuwen/go-bindata/...

    go-bindata -o bosh/deployment_files.go vendor/github.com/cppforlife/jumpbox-deployment/... vendor/github.com/cloudfoundry/bosh-deployment/...

    sed -i -- 's/^package main$/package bosh/g' bosh/deployment_files.go

    git config user.email "cf-infrastructure@pivotal.io"
    git config user.name "cf-infra-bot"

    git checkout -B "bump-deployments-ci"
    git commit -am 'Update deployments'

    cp -r . ${ROOT}/bump-deployments-ci
  popd > /dev/null
}

main
