#!/bin/bash -exu

ROOT="${PWD}"

function main() {
  mkdir -p "${GOPATH}/src/github.com/cloudfoundry"

  pushd "${ROOT}/bosh-bootloader" > /dev/null
    go get -u github.com/jteeuwen/go-bindata/...
    go-bindata -o bosh/deployment_files.go ${ROOT}/jumpbox-deployment/... ${ROOT}/bosh-deployment/...

    sed -i -- 's/^package main$/package bosh/g' bosh/deployment_files.go

    git config user.email "cf-infrastructure@pivotal.io"
    git config user.name "cf-infra-bot"

    git checkout -B "bump-deployments-ci"
    git commit -am 'Update deployments'

    cp -r . ${ROOT}/bump-deployments-ci
  popd > /dev/null
}

main
